server {
    listen 80;

    location = / {
        return 301 /the-appreciation-mirror/;
    }

    location /the-appreciation-mirror/ {
        alias /usr/share/nginx/html/the-appreciation-mirror/;
        index index.html;
        try_files $uri $uri/ /the-appreciation-mirror/index.html;
    }

    error_page 404 /the-appreciation-mirror/index.html;
}
